import { db } from '@/db';
import { products } from '@/db/schema';

async function main() {
    const now = Date.now();
    const oneDayAgo = now - 86400000;
    const twoDaysAgo = now - 172800000;
    const threeDaysAgo = now - 259200000;
    const fiveDaysAgo = now - 432000000;

    const sampleProducts = [
        {
            title: 'Neon Orchid Symphony',
            description: 'A mesmerizing fusion of electric orchids blooming in digital space. Each petal pulses with vibrant neon energy, creating a harmonious symphony of color and light.',
            imageUrl: 'https://yefggbkybkfmuhzfrnfs.supabase.co/storage/v1/object/public/artwork-images/neon-orchid-01.jpg',
            price: 89.99,
            category: 'Orchid Dreams',
            status: 'published',
            isSold: 0,
            featured: 0,
            soldTo: null,
            soldAt: null,
            orderId: null,
            createdAt: fiveDaysAgo,
            updatedAt: fiveDaysAgo,
        },
        {
            title: 'Cyber Metropolis Dreams',
            description: 'An immersive journey through towering digital skyscrapers bathed in neon lights. This cyberpunk cityscape captures the essence of a futuristic urban dreamscape.',
            imageUrl: 'https://yefggbkybkfmuhzfrnfs.supabase.co/storage/v1/object/public/artwork-images/cyber-city-01.jpg',
            price: 125.00,
            category: 'Futuristic Landscapes',
            status: 'published',
            isSold: 0,
            featured: 0,
            soldTo: null,
            soldAt: null,
            orderId: null,
            createdAt: fiveDaysAgo,
            updatedAt: fiveDaysAgo,
        },
        {
            title: 'Geometric Neon Cascade',
            description: 'Angular shapes and glowing lines converge in a cascading waterfall of geometric precision. This piece explores the intersection of mathematics and digital artistry.',
            imageUrl: 'https://yefggbkybkfmuhzfrnfs.supabase.co/storage/v1/object/public/artwork-images/geometric-neon-01.jpg',
            price: 75.00,
            category: 'Geometric Fusion',
            status: 'published',
            isSold: 0,
            featured: 0,
            soldTo: null,
            soldAt: null,
            orderId: null,
            createdAt: threeDaysAgo,
            updatedAt: threeDaysAgo,
        },
        {
            title: 'Neon Soul Portrait',
            description: 'A hauntingly beautiful portrait illuminated by ethereal neon glows. The subject\'s essence is captured through layers of digital luminescence and cyber-enhanced features.',
            imageUrl: 'https://yefggbkybkfmuhzfrnfs.supabase.co/storage/v1/object/public/artwork-images/neon-portrait-02.jpg',
            price: 110.00,
            category: 'Neon Portraits',
            status: 'published',
            isSold: 0,
            featured: 0,
            soldTo: null,
            soldAt: null,
            orderId: null,
            createdAt: twoDaysAgo,
            updatedAt: twoDaysAgo,
        },
        {
            title: 'Electric Bloom',
            description: 'Witness the birth of a digital flower as electric currents weave through organic forms. This featured masterpiece represents the perfect marriage of nature and technology.',
            imageUrl: 'https://yefggbkybkfmuhzfrnfs.supabase.co/storage/v1/object/public/artwork-images/electric-bloom-01.jpg',
            price: 150.00,
            category: 'Digital Art',
            status: 'published',
            isSold: 0,
            featured: 1,
            soldTo: null,
            soldAt: null,
            orderId: null,
            createdAt: oneDayAgo,
            updatedAt: oneDayAgo,
        },
        {
            title: 'Futuristic Cyber Portal',
            description: 'Step through this glowing gateway into another dimension. Swirling neon energies and cyber architecture create an irresistible portal to the digital unknown.',
            imageUrl: 'https://yefggbkybkfmuhzfrnfs.supabase.co/storage/v1/object/public/artwork-images/cyber-portal-01.jpg',
            price: 135.00,
            category: 'Cyber Abstract',
            status: 'published',
            isSold: 0,
            featured: 1,
            soldTo: null,
            soldAt: null,
            orderId: null,
            createdAt: oneDayAgo,
            updatedAt: oneDayAgo,
        },
        {
            title: 'Digital Orchid Garden',
            description: 'A serene digital garden where orchids bloom in pixelated perfection. Each flower exists in a state of perpetual digital spring, forever captured in algorithmic beauty.',
            imageUrl: 'https://yefggbkybkfmuhzfrnfs.supabase.co/storage/v1/object/public/artwork-images/orchid-garden-01.jpg',
            price: 95.00,
            category: 'Orchid Dreams',
            status: 'published',
            isSold: 1,
            featured: 0,
            soldTo: 'sarah.chen@example.com',
            soldAt: threeDaysAgo,
            orderId: 1,
            createdAt: fiveDaysAgo,
            updatedAt: threeDaysAgo,
        },
        {
            title: 'Orchid Cyber Fusion',
            description: 'Delicate orchid petals merge seamlessly with cyber circuitry in this stunning fusion piece. The organic and synthetic become one in perfect digital harmony.',
            imageUrl: 'https://yefggbkybkfmuhzfrnfs.supabase.co/storage/v1/object/public/artwork-images/orchid-fusion-01.jpg',
            price: 85.00,
            category: 'Orchid Dreams',
            status: 'published',
            isSold: 1,
            featured: 0,
            soldTo: 'marcus.rodriguez@example.com',
            soldAt: twoDaysAgo,
            orderId: 2,
            createdAt: fiveDaysAgo,
            updatedAt: twoDaysAgo,
        },
        {
            title: 'Holographic Orchid',
            description: 'A rare holographic orchid specimen captured in three-dimensional digital space. Its translucent petals shimmer with iridescent data streams and prismatic light.',
            imageUrl: 'https://yefggbkybkfmuhzfrnfs.supabase.co/storage/v1/object/public/artwork-images/holographic-orchid-01.jpg',
            price: 105.00,
            category: 'Orchid Dreams',
            status: 'published',
            isSold: 1,
            featured: 0,
            soldTo: 'emily.nakamura@example.com',
            soldAt: oneDayAgo,
            orderId: 3,
            createdAt: threeDaysAgo,
            updatedAt: oneDayAgo,
        },
        {
            title: 'Abstract Electric Dreams',
            description: 'Flowing electric currents form abstract patterns in this dreamlike composition. Vibrant energy streams dance across the canvas in unpredictable yet mesmerizing patterns.',
            imageUrl: 'https://yefggbkybkfmuhzfrnfs.supabase.co/storage/v1/object/public/artwork-images/electric-dreams-01.jpg',
            price: 65.00,
            category: 'Cyber Abstract',
            status: 'draft',
            isSold: 0,
            featured: 0,
            soldTo: null,
            soldAt: null,
            orderId: null,
            createdAt: now,
            updatedAt: now,
        },
        {
            title: 'Neon Grid Horizon',
            description: 'An endless grid stretches toward a glowing horizon where neon meets infinity. This minimalist piece explores the boundaries of digital space and perception.',
            imageUrl: 'https://yefggbkybkfmuhzfrnfs.supabase.co/storage/v1/object/public/artwork-images/neon-grid-01.jpg',
            price: 55.00,
            category: 'Futuristic Landscapes',
            status: 'draft',
            isSold: 0,
            featured: 0,
            soldTo: null,
            soldAt: null,
            orderId: null,
            createdAt: now,
            updatedAt: now,
        },
        {
            title: 'Cyber Orchid Essence',
            description: 'The pure essence of an orchid distilled into cyber form. Glowing data particles coalesce into the fundamental shape of nature\'s most elegant flower.',
            imageUrl: 'https://yefggbkybkfmuhzfrnfs.supabase.co/storage/v1/object/public/artwork-images/cyber-orchid-essence-01.jpg',
            price: 80.00,
            category: 'Orchid Dreams',
            status: 'draft',
            isSold: 0,
            featured: 0,
            soldTo: null,
            soldAt: null,
            orderId: null,
            createdAt: now,
            updatedAt: now,
        },
    ];

    await db.insert(products).values(sampleProducts);
    
    console.log('✅ Products seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});